-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 17:04:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wk` DEFAULT CHARACTER SET utf8 ;
USE `wk` ;

-- -----------------------------------------------------
-- Table `wk`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wk`.`CLIENTES` (
  `CODIGO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `UF` VARCHAR(2) NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wk`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wk`.`PRODUTOS` (
  `CODIGO` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(255) NULL,
  `PRECO` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wk`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wk`.`PEDIDOS` (
  `CODIGO` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NULL,
  `VALOR_TOTAL` DOUBLE NULL,
  `CLIENTE_CODIGO` INT NOT NULL,
  PRIMARY KEY (`CODIGO`),
  INDEX `fk_PEDIDOS_CLIENTES_idx` (`CLIENTE_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_CLIENTES`
    FOREIGN KEY (`CLIENTE_CODIGO`)
    REFERENCES `wk`.`CLIENTES` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wk`.`PEDIDOS_PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wk`.`PEDIDOS_PRODUTOS` (
  `CODIGO` INT NOT NULL AUTO_INCREMENT,
  `PEDIDOS_CODIGO` INT NOT NULL,
  `PRODUTOS_CODIGO` INT NOT NULL,
  `QTDE` DOUBLE NULL,
  `VALOR_UNITARIO` DOUBLE NULL,
  `VALOR_TOTAL` VARCHAR(45) NULL,
  PRIMARY KEY (`CODIGO`),
  INDEX `fk_PEDIDOS_PRODUTOS_PEDIDOS1_idx` (`PEDIDOS_CODIGO` ASC) VISIBLE,
  INDEX `fk_PEDIDOS_PRODUTOS_PRODUTOS1_idx` (`PRODUTOS_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_PRODUTOS_PEDIDOS1`
    FOREIGN KEY (`PEDIDOS_CODIGO`)
    REFERENCES `wk`.`PEDIDOS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOS_PRODUTOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_CODIGO`)
    REFERENCES `wk`.`PRODUTOS` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
